name: deployDev.yml
on:
  push:
    paths:
      - '**'
      - '!.github/workflows/**'
      - '.github/workflows/deployDev.yml'
      
permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
             inlineScript: |
               Get-AzResourceGroup
             azPSVersion: "latest"
 
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
            subscriptionId: "5dcedb53-6662-448c-bad5-9f7fb6155570"
            resourceGroupName: "AppRazor"
            template: ./ARM-Templates/container-webapp-template.json 