name: .NET

on:
  push:
    paths:
      - 'Application/**'
    branches: [ main ]
  pull_request:
    paths:
      - '/Application/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies 
      run: dotnet restore 'src/RazorPagesTestSample/RazorPagesTestSample.csproj'
    - name: Build 
      run: dotnet build 'src/RazorPagesTestSample/RazorPagesTestSample.csproj' --no-restore
    - name: Test 
      run: dotnet 'tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj' test --no-build --verbosity normal
